import Link from "next/link";
import type { Metadata } from "next";
import BookingOverview from "../components/BookingOverview";
import HoursCard from "../components/HoursCard";
import MapEmbed from "../components/MapEmbed";
import ServiceCard from "../components/ServiceCard";
import SiteFooter from "../components/SiteFooter";
import SiteHeader from "../components/SiteHeader";
import { appointmentHref, appointmentLabel, pageCopy, salonConfig, site } from "../site-data";
import { pageMetadata } from "../seo";

export const metadata: Metadata = pageMetadata("booking");

export default function BookingPage() {
  return <main className="inner-page booking-page"><SiteHeader inner /><section className="inner-hero"><div className="inner-hero-copy"><p className="eyebrow">{pageCopy.pages.booking.eyebrow}</p><h1>Termin <em className="heading-accent">anfragen.</em></h1><p>{pageCopy.pages.booking.intro}</p><div className="hero-actions"><a className="button button-primary" href={appointmentHref}>{appointmentLabel}</a><Link className="text-link" href="/oeffnungszeiten/">Kontakt ansehen <span aria-hidden="true">→</span></Link></div></div><div className="inner-hero-mark" aria-hidden="true"><span>{salonConfig.logo.mark}</span></div></section><section className="booking-page-intro"><p className="section-kicker">So funktioniert es</p><h2>Wunsch. <em className="heading-accent">Anruf.</em> Termin.</h2><p>Ein kurzer persönlicher Austausch schafft Klarheit – vom ersten Wunsch bis zur Terminbestätigung.</p><BookingOverview /></section><section className="services-section booking-services" aria-labelledby="booking-services-title"><div className="section-heading section-heading-light"><p className="section-kicker">Wunsch besprechen</p><h2 id="booking-services-title">Inspiration für den <em className="heading-accent">nächsten Look.</em></h2><p>Diese Themen sind öffentlich bei Glamour Cut zu sehen. Den konkreten Umfang und Preis klären Sie direkt im Salon.</p></div><div className="service-list">{salonConfig.services.map((service) => <ServiceCard key={service.number} {...service} href={appointmentHref} />)}</div></section><section className="booking-details-grid" aria-label="Termin- und Saloninformationen"><HoursCard /><article className="booking-details-card"><p className="section-kicker">Adresse &amp; Kontakt</p><h2>Gut vorbereitet zum <em className="heading-accent">Termin.</em></h2><p className="inner-address">{site.name}<br />{site.owner}<br />{site.address[0]}<br />{site.address[1]}</p><a className="button button-primary" href={site.phoneHref}>{site.phoneDisplay} anrufen</a></article></section><section className="booking-map-section"><div><p className="section-kicker">Anfahrt</p><h2>Bis bald bei <em className="heading-accent">Glamour Cut.</em></h2><p>Adresse und Route bleiben sichtbar. Die Karte wird erst nach einem bewussten Klick geladen.</p></div><MapEmbed directionsUrl={salonConfig.links.directionsUrl} embedUrl={salonConfig.links.mapEmbedUrl} title={salonConfig.map.title} /></section><section className="inner-note-section"><p className="section-kicker">Termin anfragen</p><h2>Jetzt persönlich mit <em className="heading-accent">Glamour Cut</em> sprechen.</h2><p>Unter {site.phoneDisplay} stimmen Sie Ihren Wunsch und den passenden Termin direkt ab.</p><a className="button button-primary" href={appointmentHref}>{appointmentLabel}</a></section><SiteFooter /><a className="mobile-call-bar" href={appointmentHref}><span aria-hidden="true">☎</span>{appointmentLabel}</a></main>;
}
