import Link from "next/link";
import type { Metadata } from "next";
import BookingOverview from "../components/BookingOverview";
import HoursCard from "../components/HoursCard";
import MapEmbed from "../components/MapEmbed";
import ServiceCard from "../components/ServiceCard";
import SiteFooter from "../components/SiteFooter";
import SiteHeader from "../components/SiteHeader";
import { bookingHref, bookingLabel, pageCopy, salonConfig, site } from "../site-data";
import { pageMetadata } from "../seo";

export const metadata: Metadata = pageMetadata("booking");

export default function BookingPage() {
  return <main className="inner-page booking-page"><SiteHeader inner /><section className="inner-hero"><div className="inner-hero-copy"><p className="eyebrow">{pageCopy.pages.booking.eyebrow}</p><h1>Termin <em className="heading-accent">buchen.</em></h1><p>{pageCopy.pages.booking.intro}</p><div className="hero-actions"><a className="button button-primary" href={bookingHref}>{bookingLabel}</a><Link className="text-link" href="/oeffnungszeiten/">Kontakt ansehen <span aria-hidden="true">→</span></Link></div></div><div className="inner-hero-mark" aria-hidden="true"><span>{salonConfig.logo.mark}</span></div></section><section className="booking-page-intro"><p className="section-kicker">So funktioniert es</p><h2>Wunsch. <em className="heading-accent">Termin.</em> Vorfreude.</h2><p>Ein klarer Ablauf schafft Ruhe – vom ersten Wunsch bis zur persönlichen Bestätigung.</p><BookingOverview /></section><section className="services-section booking-services" aria-labelledby="booking-services-title"><div className="section-heading section-heading-light"><p className="section-kicker">Wunsch auswählen</p><h2 id="booking-services-title">Alles für den <em className="heading-accent">nächsten Look.</em></h2><p>Die Themen zeigen, worüber Sie im Gespräch sprechen können. Der konkrete Leistungsumfang wird im Kundenprofil bestätigt.</p></div><div className="service-list">{salonConfig.services.map((service) => <ServiceCard key={service.number} {...service} href={bookingHref} />)}</div></section><section className="booking-details-grid" aria-label="Termin- und Saloninformationen"><HoursCard /><article className="booking-details-card"><p className="section-kicker">Adresse &amp; Kontakt</p><h2>Gut vorbereitet zum <em className="heading-accent">Termin.</em></h2><p className="inner-address">{site.name}<br />{site.owner || "Persönliche Ansprechpartner werden ergänzt."}<br />{site.address[0]}<br />{site.address[1]}</p>{site.phoneHref ? <a className="button button-primary" href={site.phoneHref}>{site.phoneDisplay} anrufen</a> : <p>Der passende Kontaktweg wird im finalen Profil sichtbar verknüpft.</p>}</article></section><section className="booking-map-section"><div><p className="section-kicker">Anfahrt</p><h2>Bis bald im <em className="heading-accent">Salon.</em></h2><p>Adresse und Route bleiben sichtbar. Die Karte wird erst nach einem bewussten Klick geladen.</p></div><MapEmbed directionsUrl={salonConfig.links.directionsUrl} embedUrl={salonConfig.links.mapEmbedUrl} title={salonConfig.map.title} /></section><section className="inner-note-section"><p className="section-kicker">Weiter zur Buchung</p><h2>Der passende nächste Schritt wartet auf <em className="heading-accent">Sie.</em></h2><p>Der bestätigte Terminweg wird im finalen Kundenprofil verlinkt.</p><a className="button button-primary" href={bookingHref}>{bookingLabel}</a></section><SiteFooter /><a className="mobile-call-bar" href={bookingHref}><span aria-hidden="true">↗</span>{bookingLabel}</a></main>;
}
